"""Creacion de tabla cursos

Revision ID: fe690ac09f81
Revises: 
Create Date: 2026-06-08 20:15:49.157511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe690ac09f81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id_curso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('instructor', sa.String(length=100), nullable=False),
    sa.Column('duracion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_curso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cursos')
    # ### end Alembic commands ###
